name: Development Deployment Pipeline

on:
  push:
    branches: [dev, staging, main]

  workflow_dispatch:

jobs:
  build:
    name: Build & Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variables
        id: vars
        run: |
          echo "##[set-output name=commit;]$(echo $GITHUB_SHA | head -c7)"

      - name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Dev Image
        if: github.ref == 'refs/heads/dev'
        id: build-dev
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile.dev
          push: true
          tags: softmaxcloud/simple-app:frontend-dev-${{ steps.vars.outputs.commit }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and Push Staging Image
        if: github.ref == 'refs/heads/staging'
        id: build-staging
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile.staging
          push: true
          tags: softmaxcloud/simple-app:frontend-staging-${{ steps.vars.outputs.commit }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and Push Prod Image
        if: github.ref == 'refs/heads/main'
        id: build-prod
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile.prod
          push: true
          tags: softmaxcloud/simple-app:frontend-prod-${{ steps.vars.outputs.commit }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
